---
services:
  pgdb:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: dracula-theme
    restart: unless-stopped

  adminer-classic:
    image: adminer:4.8.1
    depends_on:
      - pgdb
    ports:
      - 880:8080
    environment:
      ADMINER_DESIGN: dracula
      ADMINER_PLUGINS: 'tables-filter tinymce dump-alter edit-calendar edit-foreign enum-option enum-types'
      ADMINER_DEFAULT_SERVER: pgdb
    restart: unless-stopped

  adminer-dracula:
    image: adminer-dracula
    build:
      context: ./
    depends_on:
      - pgdb
    ports:
      - 888:8080
    environment:
      ADMINER_DESIGN: dracula
      ADMINER_PLUGINS: 'tables-filter tinymce dump-alter edit-calendar edit-foreign enum-option enum-types'
      ADMINER_DEFAULT_SERVER: pgdb
    restart: unless-stopped

networks:
  default:
    name: dracula-network
